### Exercise 1

Generate an array that goes from 20 to 60.

#### Solution

In [1]:
import numpy as np

my_array=np.arange(20,61);my_array

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60])

### Exercise 2

Of the previous array show the array from start to end, by 5 elements

#### Solution

In [2]:
my_array[::5]

array([20, 25, 30, 35, 40, 45, 50, 55, 60])

### Exercise 3

Take as reference the array of the exercise 1 and, show from the element 30 to the and by 2 elements

#### Solution

In [3]:
my_array[30::2]

array([50, 52, 54, 56, 58, 60])

### Exercise 4

Take as reference the array of the exercise 1 and, show the array from position -10 to the begging by -2 steps

#### Solution

In [4]:
my_array[-10::-2]

array([51, 49, 47, 45, 43, 41, 39, 37, 35, 33, 31, 29, 27, 25, 23, 21])

### Exercise 5

Create a regular matrix (a regular matrix has the same number of rows than columns) with the elements from 1 to 9

#### Solution

In [5]:
my_matrix=np.arange(0,9).reshape(3,3);my_matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Exercise 6

Take the following array

In [6]:
ej_6 = np.array([
    [10, 30, 45, 150],
    [12, 40, 20, 10]
])



Create a flat array and then, show all the elements except the first and last

#### Solution

In [7]:

ej6_flat=ej_6.flatten()
print(ej6_flat)
ej6_flat[1:len(ej6_flat)-1]

[ 10  30  45 150  12  40  20  10]


array([ 30,  45, 150,  12,  40,  20])

### Exercise 7

Create a matrix of 3x3 with all the elements from 100 to 112 (if it's possible)

#### Solution

In [8]:
# matrix3x3=np.arange(100,112).reshape(3,3)
matrix4x3=np.arange(100,112).reshape(4,3);matrix4x3

array([[100, 101, 102],
       [103, 104, 105],
       [106, 107, 108],
       [109, 110, 111]])

### Exercise 8

From the previous array, show only the values higher than 106, in wich format the values are returned ?

#### Solution

In [9]:
print(matrix4x3[matrix4x3>106])
print(type(matrix4x3))

[107 108 109 110 111]
<class 'numpy.ndarray'>


### Exercise 9

Take the following arrays 

In [10]:
one = np.arange(0, 6).reshape(2,3)
two = np.arange(6, 12).reshape(2,3)

Join both arrays so that you get an array with a `shape(2,6)` structure, finally show its transpose

#### Solution

In [11]:
three=np.concatenate((one,two),axis=1); three

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### Exercise 10

Write a program that generates a 10x10 matrix with edge elements 1 and interior elements 0.

#### Solution

In [12]:
#np.where(matrix10x10[1:9,1:9]==1, 0,1)


In [13]:
matrix10x10=np.ones((10,10));matrix10x10
matrix10x10[1:9,1:9]=0;matrix10x10


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### Exercise 11

Normalize all the elements of the array, following the Z-Score formula https://www.statisticshowto.com/probability-and-statistics/z-score/

#### Solution

In [14]:
aux = np.array([
    [1, 100, 5],
    [2, 4, 0]
])

In [15]:
normalized = (aux-aux.mean()) /aux.std() ;normalized

array([[-0.48517794,  2.2336494 , -0.37532633],
       [-0.45771504, -0.40278924, -0.51264085]])

### Exercise 12

Normalize all the elements of the array, following the Min-Max formula https://en.wikipedia.org/wiki/Feature_scaling

#### Solution

In [16]:
aux = np.array([
    [1, 100, 5],
    [2, 4, 0]
])

In [17]:
normalizedmaxmin=(aux-aux.min())/(aux.max()-aux.min());normalizedmaxmin

array([[0.01, 1.  , 0.05],
       [0.02, 0.04, 0.  ]])

### Exercise 13

Write the following arrays:
* 10 zeros
* 10 ones
* 10 sevens

#### Solution

In [18]:
arr_zeros=np.zeros(10);arr_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
arr_ones=np.ones(10);arr_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
arr_seve=np.where(arr_ones==1,7,arr_ones);arr_seve

array([7., 7., 7., 7., 7., 7., 7., 7., 7., 7.])

In [21]:
arr_seve2=np.ones(10)*7;arr_seve2

array([7., 7., 7., 7., 7., 7., 7., 7., 7., 7.])

In [22]:
arr_total=arr_zeros+arr_ones+arr_seve